# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_entity_dialog.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_create_entity_dialog(object):
    def setupUi(self, create_entity_dialog):
        create_entity_dialog.setObjectName("create_entity_dialog")
        create_entity_dialog.resize(501, 297)
        self.verticalLayout = QtGui.QVBoxLayout(create_entity_dialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.create_new_entity_label = QtGui.QLabel(create_entity_dialog)
        self.create_new_entity_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_new_entity_label.sizePolicy().hasHeightForWidth())
        self.create_new_entity_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(24)
        font.setWeight(50)
        font.setBold(False)
        self.create_new_entity_label.setFont(font)
        self.create_new_entity_label.setMargin(12)
        self.create_new_entity_label.setIndent(3)
        self.create_new_entity_label.setObjectName("create_new_entity_label")
        self.verticalLayout.addWidget(self.create_new_entity_label)
        self.create_entity_line_1 = QtGui.QFrame(create_entity_dialog)
        self.create_entity_line_1.setLineWidth(0)
        self.create_entity_line_1.setMidLineWidth(1)
        self.create_entity_line_1.setFrameShape(QtGui.QFrame.HLine)
        self.create_entity_line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.create_entity_line_1.setObjectName("create_entity_line_1")
        self.verticalLayout.addWidget(self.create_entity_line_1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setContentsMargins(22, 15, 12, -1)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.entity_name_label = QtGui.QLabel(create_entity_dialog)
        self.entity_name_label.setObjectName("entity_name_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.entity_name_label)
        self.entity_name_line_edit = QtGui.QLineEdit(create_entity_dialog)
        self.entity_name_line_edit.setMinimumSize(QtCore.QSize(320, 25))
        self.entity_name_line_edit.setFrame(True)
        self.entity_name_line_edit.setObjectName("entity_name_line_edit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.entity_name_line_edit)
        self.description_label = QtGui.QLabel(create_entity_dialog)
        self.description_label.setObjectName("description_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.description_label)
        self.description_line_edit = QtGui.QLineEdit(create_entity_dialog)
        self.description_line_edit.setMinimumSize(QtCore.QSize(320, 25))
        self.description_line_edit.setObjectName("description_line_edit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.description_line_edit)
        self.status_combo_box = QtGui.QComboBox(create_entity_dialog)
        self.status_combo_box.setObjectName("status_combo_box")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.status_combo_box)
        self.status_label = QtGui.QLabel(create_entity_dialog)
        self.status_label.setObjectName("status_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.status_label)
        self.project_label = QtGui.QLabel(create_entity_dialog)
        self.project_label.setObjectName("project_label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.project_label)
        self.project_name_label = QtGui.QLabel(create_entity_dialog)
        self.project_name_label.setObjectName("project_name_label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.project_name_label)
        self.verticalLayout.addLayout(self.formLayout)
        self.create_entity_line_2 = QtGui.QFrame(create_entity_dialog)
        self.create_entity_line_2.setLineWidth(0)
        self.create_entity_line_2.setMidLineWidth(1)
        self.create_entity_line_2.setFrameShape(QtGui.QFrame.HLine)
        self.create_entity_line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.create_entity_line_2.setObjectName("create_entity_line_2")
        self.verticalLayout.addWidget(self.create_entity_line_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setContentsMargins(-1, 9, 7, 8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancel_button = QtGui.QPushButton(create_entity_dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.create_entity_button = QtGui.QPushButton(create_entity_dialog)
        self.create_entity_button.setObjectName("create_entity_button")
        self.horizontalLayout.addWidget(self.create_entity_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(create_entity_dialog)
        QtCore.QMetaObject.connectSlotsByName(create_entity_dialog)

    def retranslateUi(self, create_entity_dialog):
        create_entity_dialog.setWindowTitle(QtGui.QApplication.translate("create_entity_dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.create_new_entity_label.setText(QtGui.QApplication.translate("create_entity_dialog", "Create a new Entity", None, QtGui.QApplication.UnicodeUTF8))
        self.entity_name_label.setText(QtGui.QApplication.translate("create_entity_dialog", "Sequence name:", None, QtGui.QApplication.UnicodeUTF8))
        self.description_label.setText(QtGui.QApplication.translate("create_entity_dialog", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("create_entity_dialog", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label.setText(QtGui.QApplication.translate("create_entity_dialog", "Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.project_name_label.setText(QtGui.QApplication.translate("create_entity_dialog", "Some project", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button.setText(QtGui.QApplication.translate("create_entity_dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.create_entity_button.setText(QtGui.QApplication.translate("create_entity_dialog", "Create Entity", None, QtGui.QApplication.UnicodeUTF8))

