# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(913, 667)
        self.main_layout = QtGui.QVBoxLayout(Dialog)
        self.main_layout.setSpacing(-1)
        self.main_layout.setContentsMargins(-1, 12, -1, 12)
        self.main_layout.setObjectName("main_layout")
        self.stackedWidget = AnimatedStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.drop_page = QtGui.QWidget()
        self.drop_page.setObjectName("drop_page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.drop_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.drop_area_label = DropAreaLabel(self.drop_page)
        self.drop_area_label.setAlignment(QtCore.Qt.AlignCenter)
        self.drop_area_label.setObjectName("drop_area_label")
        self.verticalLayout_2.addWidget(self.drop_area_label)
        self.stackedWidget.addWidget(self.drop_page)
        self.sequence_list_page = QtGui.QWidget()
        self.sequence_list_page.setObjectName("sequence_list_page")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.sequence_list_page)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtGui.QScrollArea(self.sequence_list_page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaContent = QtGui.QWidget()
        self.scrollAreaContent.setGeometry(QtCore.QRect(0, 0, 887, 535))
        self.scrollAreaContent.setObjectName("scrollAreaContent")
        self.sequence_grid = QtGui.QGridLayout(self.scrollAreaContent)
        self.sequence_grid.setContentsMargins(0, 0, 0, 0)
        self.sequence_grid.setObjectName("sequence_grid")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.sequence_grid.addItem(spacerItem, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaContent)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.sequence_list_page)
        self.cut_summary_page = QtGui.QWidget()
        self.cut_summary_page.setObjectName("cut_summary_page")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.cut_summary_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.total_button = QtGui.QPushButton(self.cut_summary_page)
        self.total_button.setCheckable(True)
        self.total_button.setChecked(False)
        self.total_button.setAutoExclusive(True)
        self.total_button.setFlat(True)
        self.total_button.setObjectName("total_button")
        self.horizontalLayout_2.addWidget(self.total_button)
        self.new_select_button = QtGui.QPushButton(self.cut_summary_page)
        self.new_select_button.setCheckable(True)
        self.new_select_button.setChecked(True)
        self.new_select_button.setAutoExclusive(True)
        self.new_select_button.setFlat(True)
        self.new_select_button.setObjectName("new_select_button")
        self.horizontalLayout_2.addWidget(self.new_select_button)
        self.omitted_select_button = QtGui.QPushButton(self.cut_summary_page)
        self.omitted_select_button.setCheckable(True)
        self.omitted_select_button.setAutoExclusive(True)
        self.omitted_select_button.setFlat(True)
        self.omitted_select_button.setObjectName("omitted_select_button")
        self.horizontalLayout_2.addWidget(self.omitted_select_button)
        self.reinstated_select_button = QtGui.QPushButton(self.cut_summary_page)
        self.reinstated_select_button.setCheckable(True)
        self.reinstated_select_button.setAutoExclusive(True)
        self.reinstated_select_button.setFlat(True)
        self.reinstated_select_button.setObjectName("reinstated_select_button")
        self.horizontalLayout_2.addWidget(self.reinstated_select_button)
        self.cut_change_select_button = QtGui.QPushButton(self.cut_summary_page)
        self.cut_change_select_button.setCheckable(True)
        self.cut_change_select_button.setAutoExclusive(True)
        self.cut_change_select_button.setFlat(True)
        self.cut_change_select_button.setObjectName("cut_change_select_button")
        self.horizontalLayout_2.addWidget(self.cut_change_select_button)
        self.rescan_select_button = QtGui.QPushButton(self.cut_summary_page)
        self.rescan_select_button.setCheckable(True)
        self.rescan_select_button.setAutoExclusive(True)
        self.rescan_select_button.setFlat(True)
        self.rescan_select_button.setObjectName("rescan_select_button")
        self.horizontalLayout_2.addWidget(self.rescan_select_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.repeated_radio_button = QtGui.QRadioButton(self.cut_summary_page)
        self.repeated_radio_button.setAutoExclusive(False)
        self.repeated_radio_button.setObjectName("repeated_radio_button")
        self.horizontalLayout_2.addWidget(self.repeated_radio_button)
        self.horizontalLayout_2.setStretch(6, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.scrollArea_2 = QtGui.QScrollArea(self.cut_summary_page)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.cut_summary_widgets = QtGui.QWidget()
        self.cut_summary_widgets.setGeometry(QtCore.QRect(0, 0, 863, 463))
        self.cut_summary_widgets.setObjectName("cut_summary_widgets")
        self.cutsummary_list = QtGui.QVBoxLayout(self.cut_summary_widgets)
        self.cutsummary_list.setSpacing(-1)
        self.cutsummary_list.setContentsMargins(0, 0, 0, 0)
        self.cutsummary_list.setObjectName("cutsummary_list")
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.cutsummary_list.addItem(spacerItem2)
        self.scrollArea_2.setWidget(self.cut_summary_widgets)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.cut_summary_page)
        self.success_page = QtGui.QWidget()
        self.success_page.setObjectName("success_page")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.success_page)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.success_frame = QtGui.QFrame(self.success_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.success_frame.sizePolicy().hasHeightForWidth())
        self.success_frame.setSizePolicy(sizePolicy)
        self.success_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.success_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.success_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.success_frame.setObjectName("success_frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.success_frame)
        self.verticalLayout_5.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.success_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/tk_multi_importcut/icon_completed.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.success_label = QtGui.QLabel(self.success_frame)
        self.success_label.setObjectName("success_label")
        self.horizontalLayout_4.addWidget(self.success_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.shotgun_button = QtGui.QPushButton(self.success_frame)
        self.shotgun_button.setObjectName("shotgun_button")
        self.horizontalLayout_5.addWidget(self.shotgun_button)
        self.horizontalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.success_frame)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.stackedWidget.addWidget(self.success_page)
        self.main_layout.addWidget(self.stackedWidget)
        self.feedback_label = QtGui.QLabel(Dialog)
        self.feedback_label.setText("")
        self.feedback_label.setWordWrap(True)
        self.feedback_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.feedback_label.setObjectName("feedback_label")
        self.main_layout.addWidget(self.feedback_label)
        self.progress_bar = QtGui.QProgressBar(Dialog)
        self.progress_bar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progress_bar.setStyleSheet("::chunk {\n"
"background-color: #2C93E2;\n"
"}\n"
"")
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.main_layout.addWidget(self.progress_bar)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_layout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_button = QtGui.QPushButton(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tk_multi_importcut/left_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_button.setIcon(icon)
        self.back_button.setFlat(True)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout.addWidget(self.back_button)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.reset_button = QtGui.QPushButton(Dialog)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.cancel_button = QtGui.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.email_button = QtGui.QPushButton(Dialog)
        self.email_button.setObjectName("email_button")
        self.horizontalLayout.addWidget(self.email_button)
        self.submit_button = QtGui.QPushButton(Dialog)
        self.submit_button.setObjectName("submit_button")
        self.horizontalLayout.addWidget(self.submit_button)
        self.main_layout.addLayout(self.horizontalLayout)
        self.main_layout.setStretch(0, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.drop_area_label.setText(QtGui.QApplication.translate("Dialog", "DRAG & DROP\n"
"EDL", None, QtGui.QApplication.UnicodeUTF8))
        self.total_button.setText(QtGui.QApplication.translate("Dialog", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.new_select_button.setText(QtGui.QApplication.translate("Dialog", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.omitted_select_button.setText(QtGui.QApplication.translate("Dialog", "Omitted", None, QtGui.QApplication.UnicodeUTF8))
        self.reinstated_select_button.setText(QtGui.QApplication.translate("Dialog", "Reinstated", None, QtGui.QApplication.UnicodeUTF8))
        self.cut_change_select_button.setText(QtGui.QApplication.translate("Dialog", "Cut Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.rescan_select_button.setText(QtGui.QApplication.translate("Dialog", "Rescan Needed", None, QtGui.QApplication.UnicodeUTF8))
        self.repeated_radio_button.setText(QtGui.QApplication.translate("Dialog", "Only Repeated", None, QtGui.QApplication.UnicodeUTF8))
        self.success_label.setText(QtGui.QApplication.translate("Dialog", "Cut Sucessfully Imported", None, QtGui.QApplication.UnicodeUTF8))
        self.shotgun_button.setText(QtGui.QApplication.translate("Dialog", "Jump to Shotgun", None, QtGui.QApplication.UnicodeUTF8))
        self.back_button.setText(QtGui.QApplication.translate("Dialog", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_button.setText(QtGui.QApplication.translate("Dialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button.setText(QtGui.QApplication.translate("Dialog", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.email_button.setText(QtGui.QApplication.translate("Dialog", "Email Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.submit_button.setText(QtGui.QApplication.translate("Dialog", "Import Cut", None, QtGui.QApplication.UnicodeUTF8))

from ..dialog import DropAreaLabel, AnimatedStackedWidget
from . import resources_rc
