# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(766, 440)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(-1)
        self.verticalLayout.setContentsMargins(-1, 12, -1, 12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = AnimatedStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.drop_page = QtGui.QWidget()
        self.drop_page.setObjectName("drop_page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.drop_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.drop_area_label = DropAreaLabel(self.drop_page)
        self.drop_area_label.setAlignment(QtCore.Qt.AlignCenter)
        self.drop_area_label.setObjectName("drop_area_label")
        self.verticalLayout_2.addWidget(self.drop_area_label)
        self.stackedWidget.addWidget(self.drop_page)
        self.sequence_list_page = QtGui.QWidget()
        self.sequence_list_page.setObjectName("sequence_list_page")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.sequence_list_page)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtGui.QScrollArea(self.sequence_list_page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaContent = QtGui.QWidget()
        self.scrollAreaContent.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaContent.setObjectName("scrollAreaContent")
        self.sequence_grid = QtGui.QGridLayout(self.scrollAreaContent)
        self.sequence_grid.setContentsMargins(0, 0, 0, 0)
        self.sequence_grid.setObjectName("sequence_grid")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.sequence_grid.addItem(spacerItem, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaContent)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.sequence_list_page)
        self.cut_summary_page = QtGui.QWidget()
        self.cut_summary_page.setObjectName("cut_summary_page")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.cut_summary_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.scrollArea_2 = QtGui.QScrollArea(self.cut_summary_page)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.cutsummary_list = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.cutsummary_list.setContentsMargins(0, 0, 0, 0)
        self.cutsummary_list.setObjectName("cutsummary_list")
        spacerItem1 = QtGui.QSpacerItem(20, 283, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.cutsummary_list.addItem(spacerItem1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.cut_summary_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.feedback_label = QtGui.QLabel(Dialog)
        self.feedback_label.setText("")
        self.feedback_label.setWordWrap(True)
        self.feedback_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.feedback_label.setObjectName("feedback_label")
        self.verticalLayout.addWidget(self.feedback_label)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_button = QtGui.QPushButton(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tk_multi_importcut/left_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_button.setIcon(icon)
        self.back_button.setFlat(True)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout.addWidget(self.back_button)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.reset_button = QtGui.QPushButton(Dialog)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.cancel_button = QtGui.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.email_button = QtGui.QPushButton(Dialog)
        self.email_button.setObjectName("email_button")
        self.horizontalLayout.addWidget(self.email_button)
        self.submit_button = QtGui.QPushButton(Dialog)
        self.submit_button.setObjectName("submit_button")
        self.horizontalLayout.addWidget(self.submit_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.drop_area_label.setText(QtGui.QApplication.translate("Dialog", "DRAG & DROP\n"
"EDL", None, QtGui.QApplication.UnicodeUTF8))
        self.back_button.setText(QtGui.QApplication.translate("Dialog", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_button.setText(QtGui.QApplication.translate("Dialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button.setText(QtGui.QApplication.translate("Dialog", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.email_button.setText(QtGui.QApplication.translate("Dialog", "Email Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.submit_button.setText(QtGui.QApplication.translate("Dialog", "Import Cut", None, QtGui.QApplication.UnicodeUTF8))

from ..dialog import DropAreaLabel, AnimatedStackedWidget
from . import resources_rc
