# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_dialog.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_settings_dialog(object):
    def setupUi(self, settings_dialog):
        settings_dialog.setObjectName("settings_dialog")
        settings_dialog.resize(523, 413)
        self.label = QtGui.QLabel(settings_dialog)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 29))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtGui.QTabWidget(settings_dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 60, 521, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.note_addressing_label = QtGui.QLabel(self.tab)
        self.note_addressing_label.setGeometry(QtCore.QRect(10, 5, 161, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.note_addressing_label.setFont(font)
        self.note_addressing_label.setObjectName("note_addressing_label")
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 241, 16))
        self.label_3.setObjectName("label_3")
        self.statuses_label = QtGui.QLabel(self.tab)
        self.statuses_label.setGeometry(QtCore.QRect(20, 60, 161, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.statuses_label.setFont(font)
        self.statuses_label.setObjectName("statuses_label")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 510, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 411, 16))
        self.label_2.setObjectName("label_2")
        self.update_shot_statuses_checkbox = QtGui.QCheckBox(self.tab)
        self.update_shot_statuses_checkbox.setGeometry(QtCore.QRect(30, 140, 171, 20))
        self.update_shot_statuses_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.update_shot_statuses_checkbox.setObjectName("update_shot_statuses_checkbox")
        self.omit_status_combo_box = QtGui.QComboBox(self.tab)
        self.omit_status_combo_box.setGeometry(QtCore.QRect(180, 170, 104, 26))
        self.omit_status_combo_box.setWhatsThis("")
        self.omit_status_combo_box.setAccessibleName("")
        self.omit_status_combo_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.omit_status_combo_box.setObjectName("omit_status_combo_box")
        self.omit_status_label = QtGui.QLabel(self.tab)
        self.omit_status_label.setEnabled(True)
        self.omit_status_label.setGeometry(QtCore.QRect(100, 170, 81, 16))
        self.omit_status_label.setObjectName("omit_status_label")
        self.reinstate_shot_if_status_is_label = QtGui.QLabel(self.tab)
        self.reinstate_shot_if_status_is_label.setEnabled(True)
        self.reinstate_shot_if_status_is_label.setGeometry(QtCore.QRect(10, 210, 171, 16))
        self.reinstate_shot_if_status_is_label.setObjectName("reinstate_shot_if_status_is_label")
        self.reinstate_shot_if_status_is_combo_box = QtGui.QComboBox(self.tab)
        self.reinstate_shot_if_status_is_combo_box.setGeometry(QtCore.QRect(180, 210, 104, 26))
        self.reinstate_shot_if_status_is_combo_box.setWhatsThis("")
        self.reinstate_shot_if_status_is_combo_box.setAccessibleName("")
        self.reinstate_shot_if_status_is_combo_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reinstate_shot_if_status_is_combo_box.setObjectName("reinstate_shot_if_status_is_combo_box")
        self.reinstate_status_label = QtGui.QLabel(self.tab)
        self.reinstate_status_label.setEnabled(True)
        self.reinstate_status_label.setGeometry(QtCore.QRect(300, 210, 111, 16))
        self.reinstate_status_label.setObjectName("reinstate_status_label")
        self.reinstate_status_combo_box = QtGui.QComboBox(self.tab)
        self.reinstate_status_combo_box.setGeometry(QtCore.QRect(410, 210, 104, 26))
        self.reinstate_status_combo_box.setWhatsThis("")
        self.reinstate_status_combo_box.setAccessibleName("")
        self.reinstate_status_combo_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reinstate_status_combo_box.setObjectName("reinstate_status_combo_box")
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 240, 171, 16))
        self.label_8.setObjectName("label_8")
        self.use_smart_fields_checkbox = QtGui.QCheckBox(self.tab)
        self.use_smart_fields_checkbox.setGeometry(QtCore.QRect(30, 270, 171, 20))
        self.use_smart_fields_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.use_smart_fields_checkbox.setObjectName("use_smart_fields_checkbox")
        self.email_group_combo_box = QtGui.QComboBox(self.tab)
        self.email_group_combo_box.setGeometry(QtCore.QRect(220, 30, 104, 26))
        self.email_group_combo_box.setWhatsThis("")
        self.email_group_combo_box.setAccessibleName("")
        self.email_group_combo_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.email_group_combo_box.setObjectName("email_group_combo_box")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(40, 30, 121, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(30, 60, 181, 16))
        self.label_11.setObjectName("label_11")
        self.timecode_to_frame_mapping_combo_box = QtGui.QComboBox(self.tab_2)
        self.timecode_to_frame_mapping_combo_box.setGeometry(QtCore.QRect(220, 60, 104, 26))
        self.timecode_to_frame_mapping_combo_box.setObjectName("timecode_to_frame_mapping_combo_box")
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(10, 90, 501, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 491, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 140, 71, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(10, 160, 501, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(10, 180, 501, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(40, 210, 101, 16))
        self.label_17.setObjectName("label_17")
        self.default_head_in_line_edit = QtGui.QLineEdit(self.tab_2)
        self.default_head_in_line_edit.setGeometry(QtCore.QRect(150, 210, 31, 21))
        self.default_head_in_line_edit.setObjectName("default_head_in_line_edit")
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(40, 250, 151, 16))
        self.label_18.setObjectName("label_18")
        self.default_head_duration_line_edit = QtGui.QLineEdit(self.tab_2)
        self.default_head_duration_line_edit.setGeometry(QtCore.QRect(190, 250, 41, 21))
        self.default_head_duration_line_edit.setObjectName("default_head_duration_line_edit")
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(250, 250, 131, 16))
        self.label_19.setObjectName("label_19")
        self.default_tail_duration_line_edit = QtGui.QLineEdit(self.tab_2)
        self.default_tail_duration_line_edit.setGeometry(QtCore.QRect(390, 250, 41, 21))
        self.default_tail_duration_line_edit.setObjectName("default_tail_duration_line_edit")
        self.default_frame_rate_line_edit = QtGui.QLineEdit(self.tab_2)
        self.default_frame_rate_line_edit.setGeometry(QtCore.QRect(170, 30, 41, 21))
        self.default_frame_rate_line_edit.setObjectName("default_frame_rate_line_edit")
        self.tabWidget.addTab(self.tab_2, "")
        self.save_settings_button_box = QtGui.QDialogButtonBox(settings_dialog)
        self.save_settings_button_box.setGeometry(QtCore.QRect(360, 380, 164, 32))
        self.save_settings_button_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save_settings_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.save_settings_button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.save_settings_button_box.setCenterButtons(False)
        self.save_settings_button_box.setObjectName("save_settings_button_box")

        self.retranslateUi(settings_dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settings_dialog)

    def retranslateUi(self, settings_dialog):
        settings_dialog.setWindowTitle(QtGui.QApplication.translate("settings_dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("settings_dialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.note_addressing_label.setText(QtGui.QApplication.translate("settings_dialog", "Note Addressing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("settings_dialog", "Send Cut Summary Note To:", None, QtGui.QApplication.UnicodeUTF8))
        self.statuses_label.setText(QtGui.QApplication.translate("settings_dialog", "Statuses", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("settings_dialog", "When a new Cut omits a Shot or reinstates a previously-omitted Shot, the app can", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("settings_dialog", "automatically update the status in Shotgun.", None, QtGui.QApplication.UnicodeUTF8))
        self.update_shot_statuses_checkbox.setText(QtGui.QApplication.translate("settings_dialog", "Update Shot Statuses:", None, QtGui.QApplication.UnicodeUTF8))
        self.omit_status_label.setText(QtGui.QApplication.translate("settings_dialog", "Omit Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.reinstate_shot_if_status_is_label.setText(QtGui.QApplication.translate("settings_dialog", "Reinstate Shot if Status is:", None, QtGui.QApplication.UnicodeUTF8))
        self.reinstate_status_label.setText(QtGui.QApplication.translate("settings_dialog", "Reinstate Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("settings_dialog", "Cut Fields on Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.use_smart_fields_checkbox.setText(QtGui.QApplication.translate("settings_dialog", "Use \"Smart\" Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("settings_dialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("settings_dialog", "Timecode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("settings_dialog", "Default Frame Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("settings_dialog", "Timecode to Frame Mapping", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("settings_dialog", "In Absolute mode, the app will map the timecode values from the EDL directly as", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("settings_dialog", "frames based on the frame rate. For example, at 24 fps 00:00:01:00 = frame 24.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("settings_dialog", "New Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("settings_dialog", "When creating new Shots in Shotgun, the app will use the following numbers for", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("settings_dialog", "start frame and handles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("settings_dialog", "Default Head In:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("settings_dialog", "Default Head Duration:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("settings_dialog", "Default Tail Duration:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("settings_dialog", "Timecode/Frames", None, QtGui.QApplication.UnicodeUTF8))

