# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'submit_dialog.ui'
#
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_submit_dialog(object):
    def setupUi(self, submit_dialog):
        submit_dialog.setObjectName("submit_dialog")
        submit_dialog.resize(400, 482)
        submit_dialog.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(submit_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(submit_dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.title_text = QtGui.QLineEdit(submit_dialog)
        self.title_text.setObjectName("title_text")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.title_text)
        self.label_2 = QtGui.QLabel(submit_dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.from_label = QtGui.QLabel(submit_dialog)
        self.from_label.setObjectName("from_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.from_label)
        self.label_4 = QtGui.QLabel(submit_dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.to_text = QtGui.QLineEdit(submit_dialog)
        self.to_text.setObjectName("to_text")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.to_text)
        self.label_5 = QtGui.QLabel(submit_dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.description_text = QtGui.QTextEdit(submit_dialog)
        self.description_text.setObjectName("description_text")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.description_text)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(1, 0, 1, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_3 = QtGui.QFrame(submit_dialog)
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 7, 0, 1, 4)
        self.label_9 = QtGui.QLabel(submit_dialog)
        self.label_9.setStyleSheet("")
        self.label_9.setMargin(0)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_3 = QtGui.QLabel(submit_dialog)
        self.label_3.setStyleSheet("")
        self.label_3.setMargin(0)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(submit_dialog)
        self.label_7.setStyleSheet("")
        self.label_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_7.setMargin(0)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(submit_dialog)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 2, 1, 1)
        self.label_6 = QtGui.QLabel(submit_dialog)
        self.label_6.setStyleSheet("border-bottom: 1px solid black;\n"
"")
        self.label_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_6.setMargin(0)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 4)
        self.rescans_label = QtGui.QLabel(submit_dialog)
        self.rescans_label.setStyleSheet("")
        self.rescans_label.setText("")
        self.rescans_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rescans_label.setObjectName("rescans_label")
        self.gridLayout.addWidget(self.rescans_label, 4, 3, 1, 1)
        self.label_11 = QtGui.QLabel(submit_dialog)
        self.label_11.setStyleSheet("")
        self.label_11.setMargin(0)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        self.repeated_label = QtGui.QLabel(submit_dialog)
        self.repeated_label.setStyleSheet("")
        self.repeated_label.setText("")
        self.repeated_label.setAlignment(QtCore.Qt.AlignCenter)
        self.repeated_label.setObjectName("repeated_label")
        self.gridLayout.addWidget(self.repeated_label, 6, 3, 1, 1)
        self.cut_changes_label = QtGui.QLabel(submit_dialog)
        self.cut_changes_label.setStyleSheet("")
        self.cut_changes_label.setText("")
        self.cut_changes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cut_changes_label.setObjectName("cut_changes_label")
        self.gridLayout.addWidget(self.cut_changes_label, 2, 3, 1, 1)
        self.total_shots_label = QtGui.QLabel(submit_dialog)
        self.total_shots_label.setStyleSheet("")
        self.total_shots_label.setText("")
        self.total_shots_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_shots_label.setObjectName("total_shots_label")
        self.gridLayout.addWidget(self.total_shots_label, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(submit_dialog)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 2, 1, 1)
        self.line_5 = QtGui.QFrame(submit_dialog)
        self.line_5.setFrameShadow(QtGui.QFrame.Plain)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 9, 0, 1, 4)
        self.new_shots_label = QtGui.QLabel(submit_dialog)
        self.new_shots_label.setStyleSheet("")
        self.new_shots_label.setText("")
        self.new_shots_label.setAlignment(QtCore.Qt.AlignCenter)
        self.new_shots_label.setObjectName("new_shots_label")
        self.gridLayout.addWidget(self.new_shots_label, 4, 1, 1, 1)
        self.line_1 = QtGui.QFrame(submit_dialog)
        self.line_1.setFrameShadow(QtGui.QFrame.Plain)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayout.addWidget(self.line_1, 1, 0, 1, 4)
        self.reinstated_label = QtGui.QLabel(submit_dialog)
        self.reinstated_label.setStyleSheet("")
        self.reinstated_label.setText("")
        self.reinstated_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reinstated_label.setObjectName("reinstated_label")
        self.gridLayout.addWidget(self.reinstated_label, 8, 1, 1, 1)
        self.omitted_label = QtGui.QLabel(submit_dialog)
        self.omitted_label.setStyleSheet("")
        self.omitted_label.setText("")
        self.omitted_label.setAlignment(QtCore.Qt.AlignCenter)
        self.omitted_label.setObjectName("omitted_label")
        self.gridLayout.addWidget(self.omitted_label, 6, 1, 1, 1)
        self.line_4 = QtGui.QFrame(submit_dialog)
        self.line_4.setFrameShadow(QtGui.QFrame.Plain)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 3, 0, 1, 4)
        self.line_2 = QtGui.QFrame(submit_dialog)
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 4)
        self.label_10 = QtGui.QLabel(submit_dialog)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.import_cut_button_box = QtGui.QDialogButtonBox(submit_dialog)
        self.import_cut_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.import_cut_button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.import_cut_button_box.setObjectName("import_cut_button_box")
        self.verticalLayout.addWidget(self.import_cut_button_box)

        self.retranslateUi(submit_dialog)
        QtCore.QMetaObject.connectSlotsByName(submit_dialog)

    def retranslateUi(self, submit_dialog):
        submit_dialog.setWindowTitle(QtGui.QApplication.translate("submit_dialog", "Import Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("submit_dialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("submit_dialog", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.from_label.setText(QtGui.QApplication.translate("submit_dialog", "me", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("submit_dialog", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("submit_dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("submit_dialog", "Omitted", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("submit_dialog", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("submit_dialog", "Total Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("submit_dialog", "Rescan Needed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("submit_dialog", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("submit_dialog", "Reinstated", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("submit_dialog", "Cut Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("submit_dialog", "Repeated", None, QtGui.QApplication.UnicodeUTF8))

