# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'submit_dialog.ui'
#
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_submit_dialog(object):
    def setupUi(self, submit_dialog):
        submit_dialog.setObjectName("submit_dialog")
        submit_dialog.resize(400, 300)
        submit_dialog.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(submit_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(submit_dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(submit_dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtGui.QLabel(submit_dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(submit_dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_3)
        self.label_4 = QtGui.QLabel(submit_dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtGui.QLineEdit(submit_dialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_5 = QtGui.QLabel(submit_dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.textEdit = QtGui.QTextEdit(submit_dialog)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.textEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtGui.QLabel(submit_dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(submit_dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(submit_dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(submit_dialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(submit_dialog)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.import_cut_button_box = QtGui.QDialogButtonBox(submit_dialog)
        self.import_cut_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.import_cut_button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.import_cut_button_box.setObjectName("import_cut_button_box")
        self.verticalLayout.addWidget(self.import_cut_button_box)

        self.retranslateUi(submit_dialog)
        QtCore.QMetaObject.connectSlotsByName(submit_dialog)

    def retranslateUi(self, submit_dialog):
        submit_dialog.setWindowTitle(QtGui.QApplication.translate("submit_dialog", "Import Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("submit_dialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("submit_dialog", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("submit_dialog", "me", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("submit_dialog", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("submit_dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("submit_dialog", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("submit_dialog", "Total Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("submit_dialog", "47", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("submit_dialog", "Cut Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("submit_dialog", "2000", None, QtGui.QApplication.UnicodeUTF8))

