# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(941, 581)
        self.main_layout = QtGui.QVBoxLayout(Dialog)
        self.main_layout.setSpacing(-1)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.stackedWidget = AnimatedStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.drop_page = QtGui.QWidget()
        self.drop_page.setObjectName("drop_page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.drop_page)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.drop_area_frame = DropAreaFrame(self.drop_page)
        self.drop_area_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.drop_area_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.drop_area_frame.setObjectName("drop_area_frame")
        self.gridLayout = QtGui.QGridLayout(self.drop_area_frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.drop_area_icon_label = QtGui.QLabel(self.drop_area_frame)
        self.drop_area_icon_label.setMaximumSize(QtCore.QSize(200, 200))
        self.drop_area_icon_label.setText("")
        self.drop_area_icon_label.setPixmap(QtGui.QPixmap(":/tk_multi_importcut/edl_file.png"))
        self.drop_area_icon_label.setScaledContents(True)
        self.drop_area_icon_label.setObjectName("drop_area_icon_label")
        self.gridLayout.addWidget(self.drop_area_icon_label, 1, 1, 1, 1)
        self.drop_area_label = QtGui.QLabel(self.drop_area_frame)
        self.drop_area_label.setAlignment(QtCore.Qt.AlignCenter)
        self.drop_area_label.setObjectName("drop_area_label")
        self.gridLayout.addWidget(self.drop_area_label, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.drop_area_frame)
        self.stackedWidget.addWidget(self.drop_page)
        self.sequence_list_page = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_list_page.sizePolicy().hasHeightForWidth())
        self.sequence_list_page.setSizePolicy(sizePolicy)
        self.sequence_list_page.setMinimumSize(QtCore.QSize(0, 0))
        self.sequence_list_page.setObjectName("sequence_list_page")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.sequence_list_page)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(12, 0, 12, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setContentsMargins(12, 4, 12, 4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sequences_label = QtGui.QLabel(self.sequence_list_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequences_label.sizePolicy().hasHeightForWidth())
        self.sequences_label.setSizePolicy(sizePolicy)
        self.sequences_label.setMinimumSize(QtCore.QSize(200, 0))
        self.sequences_label.setObjectName("sequences_label")
        self.horizontalLayout_7.addWidget(self.sequences_label)
        self.sequences_title_label = QtGui.QLabel(self.sequence_list_page)
        self.sequences_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sequences_title_label.setObjectName("sequences_title_label")
        self.horizontalLayout_7.addWidget(self.sequences_title_label)
        self.sequences_search_line_edit = SearchWidget(self.sequence_list_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequences_search_line_edit.sizePolicy().hasHeightForWidth())
        self.sequences_search_line_edit.setSizePolicy(sizePolicy)
        self.sequences_search_line_edit.setMinimumSize(QtCore.QSize(200, 30))
        self.sequences_search_line_edit.setBaseSize(QtCore.QSize(0, 0))
        self.sequences_search_line_edit.setObjectName("sequences_search_line_edit")
        self.horizontalLayout_7.addWidget(self.sequences_search_line_edit)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.sequence_scroll_area = QtGui.QScrollArea(self.sequence_list_page)
        self.sequence_scroll_area.setWidgetResizable(True)
        self.sequence_scroll_area.setObjectName("sequence_scroll_area")
        self.sequence_area = QtGui.QWidget()
        self.sequence_area.setGeometry(QtCore.QRect(0, 0, 915, 445))
        self.sequence_area.setStyleSheet("")
        self.sequence_area.setObjectName("sequence_area")
        self.sequence_grid = QtGui.QGridLayout(self.sequence_area)
        self.sequence_grid.setContentsMargins(2, 2, 2, 2)
        self.sequence_grid.setSpacing(2)
        self.sequence_grid.setObjectName("sequence_grid")
        spacerItem4 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.sequence_grid.addItem(spacerItem4, 0, 0, 1, 1)
        self.sequence_scroll_area.setWidget(self.sequence_area)
        self.verticalLayout_3.addWidget(self.sequence_scroll_area)
        self.stackedWidget.addWidget(self.sequence_list_page)
        self.cut_list_page = QtGui.QWidget()
        self.cut_list_page.setObjectName("cut_list_page")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.cut_list_page)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(12, 0, 12, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(12, 4, 12, 4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.selected_sequence_label = QtGui.QLabel(self.cut_list_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_sequence_label.sizePolicy().hasHeightForWidth())
        self.selected_sequence_label.setSizePolicy(sizePolicy)
        self.selected_sequence_label.setMinimumSize(QtCore.QSize(200, 0))
        self.selected_sequence_label.setText("")
        self.selected_sequence_label.setObjectName("selected_sequence_label")
        self.horizontalLayout_6.addWidget(self.selected_sequence_label)
        spacerItem5 = QtGui.QSpacerItem(90, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.cuts_title_label = QtGui.QLabel(self.cut_list_page)
        self.cuts_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cuts_title_label.setObjectName("cuts_title_label")
        self.horizontalLayout_6.addWidget(self.cuts_title_label)
        self.cuts_sort_button = QtGui.QPushButton(self.cut_list_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cuts_sort_button.sizePolicy().hasHeightForWidth())
        self.cuts_sort_button.setSizePolicy(sizePolicy)
        self.cuts_sort_button.setMinimumSize(QtCore.QSize(90, 0))
        self.cuts_sort_button.setBaseSize(QtCore.QSize(0, 0))
        self.cuts_sort_button.setFlat(True)
        self.cuts_sort_button.setObjectName("cuts_sort_button")
        self.horizontalLayout_6.addWidget(self.cuts_sort_button)
        self.search_line_edit = SearchWidget(self.cut_list_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_line_edit.sizePolicy().hasHeightForWidth())
        self.search_line_edit.setSizePolicy(sizePolicy)
        self.search_line_edit.setMinimumSize(QtCore.QSize(200, 30))
        self.search_line_edit.setObjectName("search_line_edit")
        self.horizontalLayout_6.addWidget(self.search_line_edit)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.scrollArea_3 = QtGui.QScrollArea(self.cut_list_page)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.cuts_area = QtGui.QWidget()
        self.cuts_area.setGeometry(QtCore.QRect(0, 0, 915, 443))
        self.cuts_area.setObjectName("cuts_area")
        self.cuts_grid = QtGui.QGridLayout(self.cuts_area)
        self.cuts_grid.setContentsMargins(2, 2, 2, 2)
        self.cuts_grid.setSpacing(2)
        self.cuts_grid.setObjectName("cuts_grid")
        spacerItem6 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.cuts_grid.addItem(spacerItem6, 1, 0, 1, 1)
        self.scrollArea_3.setWidget(self.cuts_area)
        self.verticalLayout_6.addWidget(self.scrollArea_3)
        self.stackedWidget.addWidget(self.cut_list_page)
        self.cut_summary_page = QtGui.QWidget()
        self.cut_summary_page.setObjectName("cut_summary_page")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.cut_summary_page)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cut_summary_selectors_frame = QtGui.QFrame(self.cut_summary_page)
        self.cut_summary_selectors_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.cut_summary_selectors_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.cut_summary_selectors_frame.setObjectName("cut_summary_selectors_frame")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.cut_summary_selectors_frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.total_button = QtGui.QPushButton(self.cut_summary_selectors_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_button.sizePolicy().hasHeightForWidth())
        self.total_button.setSizePolicy(sizePolicy)
        self.total_button.setMinimumSize(QtCore.QSize(70, 20))
        self.total_button.setBaseSize(QtCore.QSize(0, 70))
        self.total_button.setCheckable(True)
        self.total_button.setChecked(True)
        self.total_button.setAutoExclusive(True)
        self.total_button.setFlat(True)
        self.total_button.setObjectName("total_button")
        self.horizontalLayout_8.addWidget(self.total_button)
        self.new_select_button = QtGui.QPushButton(self.cut_summary_selectors_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_select_button.sizePolicy().hasHeightForWidth())
        self.new_select_button.setSizePolicy(sizePolicy)
        self.new_select_button.setBaseSize(QtCore.QSize(0, 70))
        self.new_select_button.setCheckable(True)
        self.new_select_button.setChecked(False)
        self.new_select_button.setAutoExclusive(True)
        self.new_select_button.setFlat(True)
        self.new_select_button.setObjectName("new_select_button")
        self.horizontalLayout_8.addWidget(self.new_select_button)
        self.omitted_select_button = QtGui.QPushButton(self.cut_summary_selectors_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.omitted_select_button.sizePolicy().hasHeightForWidth())
        self.omitted_select_button.setSizePolicy(sizePolicy)
        self.omitted_select_button.setBaseSize(QtCore.QSize(0, 70))
        self.omitted_select_button.setCheckable(True)
        self.omitted_select_button.setAutoExclusive(True)
        self.omitted_select_button.setFlat(True)
        self.omitted_select_button.setObjectName("omitted_select_button")
        self.horizontalLayout_8.addWidget(self.omitted_select_button)
        self.reinstated_select_button = QtGui.QPushButton(self.cut_summary_selectors_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reinstated_select_button.sizePolicy().hasHeightForWidth())
        self.reinstated_select_button.setSizePolicy(sizePolicy)
        self.reinstated_select_button.setBaseSize(QtCore.QSize(0, 70))
        self.reinstated_select_button.setCheckable(True)
        self.reinstated_select_button.setAutoExclusive(True)
        self.reinstated_select_button.setFlat(True)
        self.reinstated_select_button.setObjectName("reinstated_select_button")
        self.horizontalLayout_8.addWidget(self.reinstated_select_button)
        self.cut_change_select_button = QtGui.QPushButton(self.cut_summary_selectors_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cut_change_select_button.sizePolicy().hasHeightForWidth())
        self.cut_change_select_button.setSizePolicy(sizePolicy)
        self.cut_change_select_button.setBaseSize(QtCore.QSize(0, 70))
        self.cut_change_select_button.setCheckable(True)
        self.cut_change_select_button.setAutoExclusive(True)
        self.cut_change_select_button.setFlat(True)
        self.cut_change_select_button.setObjectName("cut_change_select_button")
        self.horizontalLayout_8.addWidget(self.cut_change_select_button)
        self.rescan_select_button = QtGui.QPushButton(self.cut_summary_selectors_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rescan_select_button.sizePolicy().hasHeightForWidth())
        self.rescan_select_button.setSizePolicy(sizePolicy)
        self.rescan_select_button.setBaseSize(QtCore.QSize(0, 70))
        self.rescan_select_button.setCheckable(True)
        self.rescan_select_button.setAutoExclusive(True)
        self.rescan_select_button.setFlat(True)
        self.rescan_select_button.setObjectName("rescan_select_button")
        self.horizontalLayout_8.addWidget(self.rescan_select_button)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.only_vfx_check_box = QtGui.QCheckBox(self.cut_summary_selectors_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.only_vfx_check_box.sizePolicy().hasHeightForWidth())
        self.only_vfx_check_box.setSizePolicy(sizePolicy)
        self.only_vfx_check_box.setObjectName("only_vfx_check_box")
        self.horizontalLayout_8.addWidget(self.only_vfx_check_box)
        self.horizontalLayout_8.setStretch(6, 1)
        self.verticalLayout_4.addWidget(self.cut_summary_selectors_frame)
        self.line_2 = QtGui.QFrame(self.cut_summary_page)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(12, -1, 12, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cut_summary_title_label = QtGui.QLabel(self.cut_summary_page)
        self.cut_summary_title_label.setMinimumSize(QtCore.QSize(0, 30))
        self.cut_summary_title_label.setText("")
        self.cut_summary_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cut_summary_title_label.setObjectName("cut_summary_title_label")
        self.verticalLayout_7.addWidget(self.cut_summary_title_label)
        self.scrollArea_2 = QtGui.QScrollArea(self.cut_summary_page)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.cut_summary_widgets = QtGui.QWidget()
        self.cut_summary_widgets.setGeometry(QtCore.QRect(0, 0, 915, 383))
        self.cut_summary_widgets.setObjectName("cut_summary_widgets")
        self.cutsummary_list = QtGui.QVBoxLayout(self.cut_summary_widgets)
        self.cutsummary_list.setSpacing(2)
        self.cutsummary_list.setContentsMargins(2, 2, 2, 2)
        self.cutsummary_list.setObjectName("cutsummary_list")
        spacerItem8 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.cutsummary_list.addItem(spacerItem8)
        self.scrollArea_2.setWidget(self.cut_summary_widgets)
        self.verticalLayout_7.addWidget(self.scrollArea_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        self.stackedWidget.addWidget(self.cut_summary_page)
        self.progress_page = QtGui.QWidget()
        self.progress_page.setObjectName("progress_page")
        self.gridLayout_2 = QtGui.QGridLayout(self.progress_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 2, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 2, 2, 1, 1)
        self.progress_bar = QtGui.QProgressBar(self.progress_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
        self.progress_bar.setSizePolicy(sizePolicy)
        self.progress_bar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout_2.addWidget(self.progress_bar, 2, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 4, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 0, 1, 1, 1)
        self.progress_bar_label = QtGui.QLabel(self.progress_page)
        self.progress_bar_label.setText("")
        self.progress_bar_label.setWordWrap(True)
        self.progress_bar_label.setObjectName("progress_bar_label")
        self.gridLayout_2.addWidget(self.progress_bar_label, 3, 1, 1, 1)
        self.progress_screen_title_label = QtGui.QLabel(self.progress_page)
        self.progress_screen_title_label.setObjectName("progress_screen_title_label")
        self.gridLayout_2.addWidget(self.progress_screen_title_label, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.stackedWidget.addWidget(self.progress_page)
        self.success_page = QtGui.QWidget()
        self.success_page.setObjectName("success_page")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.success_page)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.success_frame = QtGui.QFrame(self.success_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.success_frame.sizePolicy().hasHeightForWidth())
        self.success_frame.setSizePolicy(sizePolicy)
        self.success_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.success_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.success_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.success_frame.setObjectName("success_frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.success_frame)
        self.verticalLayout_5.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.success_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/tk_multi_importcut/icon_completed.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.success_label = QtGui.QLabel(self.success_frame)
        self.success_label.setObjectName("success_label")
        self.horizontalLayout_4.addWidget(self.success_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.shotgun_button = QtGui.QPushButton(self.success_frame)
        self.shotgun_button.setObjectName("shotgun_button")
        self.horizontalLayout_5.addWidget(self.shotgun_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.success_frame)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.stackedWidget.addWidget(self.success_page)
        self.main_layout.addWidget(self.stackedWidget)
        self.feedback_label = QtGui.QLabel(Dialog)
        self.feedback_label.setFrameShape(QtGui.QFrame.NoFrame)
        self.feedback_label.setFrameShadow(QtGui.QFrame.Plain)
        self.feedback_label.setText("")
        self.feedback_label.setWordWrap(True)
        self.feedback_label.setMargin(0)
        self.feedback_label.setIndent(10)
        self.feedback_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.feedback_label.setObjectName("feedback_label")
        self.main_layout.addWidget(self.feedback_label)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_layout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(12, 0, 12, 12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_button = QtGui.QPushButton(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tk_multi_importcut/left_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_button.setIcon(icon)
        self.back_button.setFlat(True)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout.addWidget(self.back_button)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem17)
        self.cancel_button = QtGui.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.reset_button = QtGui.QPushButton(Dialog)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.email_button = QtGui.QPushButton(Dialog)
        self.email_button.setObjectName("email_button")
        self.horizontalLayout.addWidget(self.email_button)
        self.submit_button = QtGui.QPushButton(Dialog)
        self.submit_button.setObjectName("submit_button")
        self.horizontalLayout.addWidget(self.submit_button)
        self.select_button = QtGui.QPushButton(Dialog)
        self.select_button.setObjectName("select_button")
        self.horizontalLayout.addWidget(self.select_button)
        self.horizontalLayout.setStretch(1, 1)
        self.main_layout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.drop_area_label.setText(QtGui.QApplication.translate("Dialog", "DRAG & DROP\n"
"EDL", None, QtGui.QApplication.UnicodeUTF8))
        self.sequences_label.setText(QtGui.QApplication.translate("Dialog", "Treating blah.edl", None, QtGui.QApplication.UnicodeUTF8))
        self.sequences_title_label.setText(QtGui.QApplication.translate("Dialog", "Select Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.sequences_search_line_edit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Search Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.cuts_title_label.setText(QtGui.QApplication.translate("Dialog", "Select Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.cuts_sort_button.setText(QtGui.QApplication.translate("Dialog", "Sort ...", None, QtGui.QApplication.UnicodeUTF8))
        self.search_line_edit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Search Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.total_button.setText(QtGui.QApplication.translate("Dialog", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.new_select_button.setText(QtGui.QApplication.translate("Dialog", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.omitted_select_button.setText(QtGui.QApplication.translate("Dialog", "Omitted", None, QtGui.QApplication.UnicodeUTF8))
        self.reinstated_select_button.setText(QtGui.QApplication.translate("Dialog", "Reinstated", None, QtGui.QApplication.UnicodeUTF8))
        self.cut_change_select_button.setText(QtGui.QApplication.translate("Dialog", "Cut Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.rescan_select_button.setText(QtGui.QApplication.translate("Dialog", "Rescan Needed", None, QtGui.QApplication.UnicodeUTF8))
        self.only_vfx_check_box.setText(QtGui.QApplication.translate("Dialog", "Hide Non-VFX Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.progress_screen_title_label.setText(QtGui.QApplication.translate("Dialog", "Importing ....", None, QtGui.QApplication.UnicodeUTF8))
        self.success_label.setText(QtGui.QApplication.translate("Dialog", "Cut Sucessfully Imported", None, QtGui.QApplication.UnicodeUTF8))
        self.shotgun_button.setText(QtGui.QApplication.translate("Dialog", "View in Shotgun", None, QtGui.QApplication.UnicodeUTF8))
        self.back_button.setText(QtGui.QApplication.translate("Dialog", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button.setText(QtGui.QApplication.translate("Dialog", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_button.setText(QtGui.QApplication.translate("Dialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.email_button.setText(QtGui.QApplication.translate("Dialog", "Email Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.submit_button.setText(QtGui.QApplication.translate("Dialog", "Import Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.select_button.setText(QtGui.QApplication.translate("Dialog", "Select", None, QtGui.QApplication.UnicodeUTF8))

from ..dialog import SearchWidget, DropAreaFrame, AnimatedStackedWidget
from . import resources_rc
